version: 1.0.{build}
clone_depth: 5
force_https_clone: true
environment:
  REPO_CLONE_ATTEMPTS: 5
  REPO_CLONE_TIMEOUT: 180
  REPO_CLONE_PROTOCOL: https
  buildconfig: Release
  buildconfig_publish: ReleaseNoTestDeploy
  nugetsprefix: ServiceStack.Webhooks.*
  symbolsourcekey: NEED_AN_API_KEY_FROM_MYGET
  matrix:
  - test_type: Unit.Testing
    test_assemblies: Webhooks.UnitTests\bin\$env:buildconfig\ServiceStack.Webhooks.UnitTests.dll;Webhooks.Interfaces.UnitTests\bin\$env:buildconfig\ServiceStack.Webhooks.Interfaces.UnitTests.dll;Webhooks.Azure.UnitTests\bin\$env:buildconfig\ServiceStack.Webhooks.Azure.UnitTests.dll
    test_category: Unit
    test_settings:
  - test_type: Integration.Testing
    test_assemblies: Webhooks.IntTests\bin\$env:buildconfig\ServiceStack.Webhooks.IntTests.dll;Webhooks.Azure.IntTests\bin\$env:buildconfig\ServiceStack.Webhooks.Azure.IntTests.dll
    test_category: Integration
    test_settings: 
matrix:
    fast_finish: false
init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
clone_script:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/clone-repo-retry.ps1'))
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/jezzsantos/ServiceStack.Webhooks/master/ci/set-version-from-assemblyinformationalversion.ps1'))
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/jezzsantos/ServiceStack.Webhooks/master/ci/install-redis-server.ps1'))
build_script:
- cd src
- cd .nuget
- appveyor-retry nuget.exe restore ..\ServiceStack.Webhooks.sln -DisableParallelProcessing
- cd ..
- msbuild.exe ServiceStack.Webhooks.sln /t:Rebuild /p:Configuration=%buildconfig% /verbosity:minimal
- cd..
test_script:
- ps: >-
    cd src

    $env:test_assemblies.Split(';') | % {
      $assemblyName = $ExecutionContext.InvokeCommand.ExpandString($_)

      &nunit3-console $assemblyName --result=TestResults.xml;format=AppVeyor

      if ($global:LASTEXITCODE -ne 0){
        $host.SetShouldExit($global:LASTEXITCODE)
        break
      }
    }

    cd..
after_test:
- ps: |
    cd src
    msbuild ServiceStack.Webhooks.sln /t:Rebuild "/p:Configuration=$env:buildconfig_publish /verbosity:minimal
    cd..

    if ($global:LASTEXITCODE -ne 0){
      $host.SetShouldExit($global:LASTEXITCODE)
      break
    }

    Get-ChildItem -Recurse .\$env:nugetsprefix.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    # Get-ChildItem -Recurse .\$env:nugetsprefix.symbols.nupkg | % { nuget push $_.FullName $env:symbolsourcekey -Source https://www.myget.org/F/jezzsantos/api/v2/package }
deploy: off

